SELECT
  'Quem depende dessa tabela' AS "descricao"
  , b.constraint_schema
  , b.CONSTRAINT_NAME
  , b.UNIQUE_CONSTRAINT_NAME
  , b.table_name 
  , a.COLUMN_NAME
  , a.REFERENCED_TABLE_NAME
  , a.REFERENCED_COLUMN_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE a
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS b 
    ON a.CONSTRAINT_NAME = b.CONSTRAINT_NAME
    AND a.CONSTRAINT_SCHEMA = b.CONSTRAINT_SCHEMA
WHERE
    a.TABLE_SCHEMA = "db_name" AND
    a.REFERENCED_TABLE_NAME = 'cliente'
ORDER BY a.TABLE_NAME ASC;

---- De que chaves a tabela depende
SELECT
  'De quem essa tabela depende' AS "descricao"
  , b.constraint_schema
  , b.CONSTRAINT_NAME
  , b.UNIQUE_CONSTRAINT_NAME
  , b.table_name 
  , a.COLUMN_NAME
  , a.REFERENCED_TABLE_NAME
  , a.REFERENCED_COLUMN_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE a
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS b 
    ON a.CONSTRAINT_NAME = b.CONSTRAINT_NAME
    AND a.CONSTRAINT_SCHEMA = b.CONSTRAINT_SCHEMA
WHERE
    a.TABLE_SCHEMA = "db_name" AND
    a.TABLE_NAME = 'cliente'
ORDER BY a.TABLE_NAME ASC;


